sonata_admin:
    title: Bookstore
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ app.admin.group.Book ]


        groups:
            app.admin.group.Book:
                label: Книги
                label_catalogue: AppBundle
                items:
                - app.admin.book_type
                - app.admin.book
                - app.admin.book_comment
